### ISSUE TITLE
MQTT broken on Windows

### ISSUE THREAD

**Issue by RuthgerD** [ItJustWorksTM/libSMCE#22]
Observed issues:
It can connect, but won't receive any messages
If it can't connect it will hang forever

**Comment by AeroStun** [comment]
Try running with `MQTT_C_CLIENT_TRACE=ON`

**Comment by AeroStun** [comment]
In fact just see https://www.eclipse.org/paho/files/mqttdoc/MQTTClient/html/tracing.html

**Comment by AeroStun** [comment]
Fixed by https://github.com/ItJustWorksTM/libSMCE/commit/c1da0ab36f52a15fa3e77818ad190f71f36d71e1
